### ISSUE TITLE
document relation to sadi's gcode repo

### ISSUE THREAD

**Issue by timrdf** [nicholasdelrio/sadi#1]
How does this repo relate to the original https://code.google.com/p/sadi/source/browse/ ?

I'm looking to fork their code to graduate to apache jena. Should I fork theirs or yours? What functionality did you add/remove?

Thanks,
Tim

**Comment by nicholasdelrio** [comment]
Mine contains a subset (1 directory named sadi.share) of their trunk. The
share client is the agent that knows how to piece together chains of
services to answer a sparql queries. I modded it to record some level of
provenance from the client's perspective.

I think you'll probably end up modding sadi.skeleton or sadi.webapp I think.

Thanks,
Nick

On Sun, Jul 6, 2014 at 1:42 PM, Tim L notifications@github.com wrote:

> How does this repo relate to the original
> https://code.google.com/p/sadi/source/browse/ ?
> 
> I'm looking to fork their code to graduate to apache jena. Should I fork
> theirs or yours? What functionality did you add/remove?
> 
> Thanks,
> Tim
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nicholasdelrio/sadi/issues/1.

## 

Nicholas Del Rio
UTEP Computer Science

**Comment by nicholasdelrio** [comment]
Lemme know if we can divi up work on this!  Sounds fun :)

**Comment by timrdf** [comment]
Thanks for the info!
